### ISSUE TITLE
rare negative upper bound exceeding

### ISSUE THREAD

**Issue by mlb2251** [mlb2251/stitch#116]
`cargo run --bin=compress --release -- -a 3 --iterations 10 --fmt=dreamcoder data/dc/logo_iteration_1.json --track="(lam (logo_forLoop #0 (lam #1) $0))" --no-opt` crashes with

```
[TRACK] pushed (lam ??) to worklist (bound: 828910)
thread 'main' panicked at '(#1 $1 #0): utility_upper_bound=-251, body_utility=102, match_locations=1, usages=1 BUT utility is higher: -153', src/compression.rs:996:9
```

this is somewhat obscure since it's a messed up invention that was only accepted because of no-opt and track but still worthwhile

**Comment by mlb2251** [comment]
`cargo run --bin=compress --release -- -a 3 --iterations 10 --fmt=dreamcoder data/dc/logo_iteration_1.json --no-opt`

`thread 'main' panicked at '(#1 $1 #0): utility_upper_bound=-251, body_utility=102, match_locations=1, usages=1 BUT utility is higher: -153 (usages: 1)', src/compression.rs:996:9`

**Comment by mlb2251** [comment]
this goes away when doing --no-other-util

**Comment by mlb2251** [comment]
ohh i see its because of the change I made to add `upper_bound_body_utility` which now that i think about it doesnt quite make sense bc for struct penalty you actually want a lower bound body utility bc it gets a negative multiplier.

What i did was fair but it means yeah we no longer have true upper bounds when theres only 1 match loc.

Also I think this honestly might mess with the loc=1 things that arent arity0 and they have free vars, bc now suddenlyt his upper bound is being passed in as a lower bound
